server:
  host: "0.0.0.0"
  port: 8090

openapi:
  base: "https://openapi.suanli.cn"
  version: "1.0.0"

auth:
  enabled: true
  api_keys:
    - "ZZqBXKauULKqic47r3nuCiGVnGOh7nwrydBUYwWCj-U"
    - "PQiMfgxplW2FcSwVlqJnc_vqz_K54qT2sXx_XLbAZo8"
    - "WJaoJtOFREl0hXtzou1AOe7r_JljIi_7sUEsqzKLigE"

projects:
  hunyuanworld-mirror:
    public_model: "kokoni-3d-world"
    task_id: 1554725
    service_port: 10085
    token: "f2ee1c4c-b678-4b3e-850b-e56a6f57bfd3-20260208093806"
    ready_timeout_sec: 300
    max_points: 2
    scale_out_timeout_sec: 300
    dispatch_retry_interval_ms: 2000
    dispatch_retry_backoff_max_ms: 5000
  hunyuanworld-mirror-cu128:
    public_model: "kokoni-3d-world-cu128"
    task_id: 1558859
    service_port: 10085
    token: "f2ee1c4c-b678-4b3e-850b-e56a6f57bfd3-20260208093806"
    ready_timeout_sec: 300
    max_points: 2
    scale_out_timeout_sec: 300
    dispatch_retry_interval_ms: 2000
    dispatch_retry_backoff_max_ms: 5000
  lightx2v:
    task_id: 1319239
    service_port: 10085
    token: "f2ee1c4c-b678-4b3e-850b-e56a6f57bfd3-20260208093806"
    ready_timeout_sec: 300
    max_points: 1
    scale_out_timeout_sec: 300
    dispatch_retry_interval_ms: 2000
    dispatch_retry_backoff_max_ms: 5000
  fastgs:
    task_id: 1573688
    service_port: 8000
    token: "f2ee1c4c-b678-4b3e-850b-e56a6f57bfd3-20260208093806"
    ready_timeout_sec: 300
    max_points: 1
    scale_out_timeout_sec: 300
    dispatch_retry_interval_ms: 2000
    dispatch_retry_backoff_max_ms: 5000
  ultrashape:
    task_id: 1650806
    service_port: 10083
    token: "f2ee1c4c-b678-4b3e-850b-e56a6f57bfd3-20260208093806"
    ready_timeout_sec: 300
    max_points: 1
    scale_out_timeout_sec: 300
    dispatch_retry_interval_ms: 2000
    dispatch_retry_backoff_max_ms: 5000
